project:
  type: website

website:
  title: "Zeki Akyol"
  description: "Personal website"
  favicon: logo.png
  site-url: https://zekiakyol.com
  repo-url: https://github.com/zekiakyol/personal-website
  navbar:
    pinned: true
    background: dark
    foreground: light
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research.qmd
        href: https://zekiakyol.com/research
      - text: "Teaching"
        file: teaching.qmd
        href: https://zekiakyol.com/teaching
      - text: "Blog"
        file: blog.qmd
        href: https://zekiakyol.com/blog
    right:
      - icon: github
        href: https://github.com/zekiakyol
      - icon: twitter
        href: https://twitter.com/zekiakyol0
      - icon: youtube
        href: https://www.youtube.com/channel/UCg4zn4AWLkuAmsPuatG6XLw
    margin-footer: | 
      This page brought to you by <https://example.com>
format:
  html:
    theme: cosmo
    css: styles.css
    linkcolor: blue