project:
  type: website

website:
  title: "Zeki Akyol"
  description: "Personal Website"
  favicon: favicon.png
  site-url: https://zekiakyol.com
  repo-url: https://github.com/zekiakyol/personal-website
  twitter-card: true
  open-graph: true
  navbar:
    pinned: true
    background: dark
    foreground: light
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Reading"
        file: reading.qmd
      - text: "Photos"
        file: photos.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: twitter
        href: https://x.com/zekiakyol0
      - icon: bluesky
        href: https://bsky.app/profile/zekiakyol.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/zekiakyol
      - icon: github
        href: https://github.com/zekiakyol
      - icon: youtube
        href: https://www.youtube.com/@zekiakyol

format:
  html:
    theme: cosmo
    css: styles.css
    linkcolor: blue