---
title: "Research"
page-layout: article
---

```{r}
#| include: false
library(fontawesome)
```

# Work in Progress

`r fa("scroll")` The Long-term Impact of Refugees in Labor Market: Evidence from Syrian Refugees in Turkey <br>
  (with Aysegul Kayaoglu)
  
# Research Experience

- **Research Assistant** in the Department of Economics `r fa("calendar-days")` (03/2021 - 08/2025) <br>
  Istanbul Technical University

- **Research Assistant** to Aysegul Kayaoglu `r fa("calendar-days")` (07/2020 - 08/2025) <br>
  Istanbul Technical University

- **Research Assistant (Data Quality Lead)** to Umut Kuruüzüm `r fa("calendar-days")` (06/2025 - 08/2025) <br>
  Supply Chain and Child Labor Analysis in Tobacco, in partnership with ICF and the U.S. Department of Labor
  
- **Research Assistant (Data Quality Lead)** to Umut Kuruüzüm `r fa("calendar-days")` (06/2024 - 09/2024) <br>
  Supply Chain and Child Labor Analysis in Cotton, in partnership with ICF and the U.S. Department of Labor
  
- **Research Assistant** to Aysun Hiziroglu Aygun `r fa("calendar-days")` (11/2022 - 11/2023)<br>
  Funded by Scientific and Technological Research Council of Turkey / TÜBİTAK-221S893 (Hasan Güçlü) <br>
  Modeling and Simulation of Infectious Diseases from Epidemiological and Economic Perspectives Using Mathematical and Agent-Based Methods 

- **Research Assistant** to Aysegul Kayaoglu `r fa("calendar-days")` (10/2021 - 07/2022) <br>
  UNICEF Turkey, Consultancy on Child Labor Legislation and Policy Improvement

- **Research Assistant (Interviewer)** `r fa("calendar-days")` (11/2020 - 01/2021) <br>
  [`r fa("link")` A. Kayaoglu (2021), A Youth Centered Participatory Assessment in Turkey: Understanding Refugee and Host Community Youth's Perceptions, Challenges and Needs. *London, Save the Children International.*](https://resourcecentre.savethechildren.net/document/a-youth-centered-participatory-assessment-in-turkey-understanding-refugee-and-host-community-youths-perceptions-challenges-and-needs){target="_blank"}

- **Research Assistant (Data Coding Team)** `r fa("calendar-days")` (02/2020 - 03/2020) <br>
  [`r fa("link")` A. Kayaoglu (2021), A Gender-sensitive Study on Urban Child Labor in Istanbul. *London, Save the Children International.*](https://resourcecentre.savethechildren.net/document/gender-sensitive-study-urban-child-labour-istanbul){target="_blank"}
  
- **Research Assistant (Field Translator, English-Turkish)** `r fa("calendar-days")` (01/2020 - 02/2020) <br>
  Funded by Ministry of Science and Technology of Taiwan; MOST Young Scholar Fellowship / 108-2636-H <br>
  [`r fa("link")` C. A. Chang (2021), The Economically Rich Refugees: A Case Study of the Business Operations of Istanbul-based Syrian Refugee Businesspeople. *International Migration.*](https://onlinelibrary.wiley.com/doi/10.1111/imig.12886){target="_blank"}

# Book

`r fa("book")` R Companion for Introduction to Econometrics (Stock and Watson, 4th Edition 2019) `r fa("calendar-days")` (Expected 2026) <br>
  (with Osman Dogan and Suleyman Taspinar)

`r fa("book")` Solution Manual for Book of Proof - Richard Hammack (3.4 Edition, 2025) `r fa("calendar-days")` (Expected 2026) <br>
  Progress: 95%
